inputs_def:
  - handle: html_content
    json_schema:
      type: string
      ui:widget: text
    description: "%html-content-to-convert%"
    nullable: false

  - handle: title
    json_schema:
      type: string
    description: "%document-title-optional%"
    value: ""
    nullable: true

  - handle: output_path
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        filters:
          - name: PDF
            extensions:
              - pdf
        excludeAll: true
    description: "%output-pdf-file-path-optional%"
    value:
    nullable: true

outputs_def:
  - handle: pdf_path
    json_schema:
      type: string
    description: "%generated-pdf-file-path%"
    nullable: false

executor:
  name: python
  options:
    entry: __init__.py

title: "%html-to-pdf%"
icon: ":carbon:document-pdf:"
description: "%convert-html-content-to-pdf-with-full-css-support%"
